### ISSUE TITLE
about thread pool

### ISSUE THREAD

**Issue by hxxfff** [google/ruy#108]
would you consider to add support for reenterable task?

currently, the tasks are not   reenterable,  in ThreadPool::ExecuteImpl,each can run in one thread;
`_void ThreadPool::ExecuteImpl(int task_count, int stride, Task* tasks) ;_` 
if use  reenterable task with atomic variable, maybe higher performance,  the overhead is light, because there is only one task. _the code: 
`_void ThreadPool::ExecuteReenterableImpl(int thread_count, Task* reenterableTask) _{__
  _RUY_DCHECK_GE(thread_count, 1);

  _// Case of 1 thread: just run the single task on the current thread.
  if (thread_count == 1) {
    (reenterableTask)->Run();
    return;
  }_

  // Task #0 will be run on the current thread.
  CreateThreads(thread_count- 1);
  counter_to_decrement_when_ready_.Reset(thread_count- 1);
  for (int i = 1; i < thread_count; i++) {
    auto task_address = reinterpret_cast<std::uintptr_t>( reenterableTask) ;//+ i * stride;
    threads_[i - 1]->StartWork(reinterpret_cast<Task*>(task_address));
  }

  // Execute task #0 immediately on the current thread.
  (reenterableTask )->Run();

  // Wait for the threads submitted above to finish.
  counter_to_decrement_when_ready_.Wait(spin_duration_);
}___`

**Comment by bjacob** [comment]
sorry about the lack of response. we don't have short term plans to modify threadpool.
