### ISSUE TITLE
Documents about the design

### ISSUE THREAD

**Issue by Leslie-Fang** [google/ruy#205]
Is there any documents about the design of Ruy? Maybe it can help us to understand the source code.
Thanks in advance.

**Comment by Leslie-Fang** [comment]
BTW: What's the difference between pack_avx512 and kernel_avx512?

**Comment by bjacob** [comment]
indeed we should write design docs.
Some existing comments play that role, in particular to your question, the general idea of 'packing' is as explained here,
https://github.com/google/ruy/blob/master/ruy/pack.h#L16
ruy's kernels don't directly read from the source matrices. they read from internal intermediate "packed" matrices created by the packing code.

**Comment by Leslie-Fang** [comment]
Thanks for the kind explanation. Close it now.
