### ISSUE TITLE
Some discussion about memalign on SystemAlignAlloc?

### ISSUE THREAD

**Issue by SunAriesCN** [google/ruy#257]
Following the TF [issue](https://github.com/tensorflow/tensorflow/issues/47712), we found the code [here](https://github.com/google/ruy/blob/3c363dc10d06857ad489c034ebb3bbd6d273dfbd/ruy/system_aligned_alloc.cc#L34), calling the memalign as SystemAlignedAlloc without any assert, is a little bit dangerous and really unfriendly for developers to debug, if some phones have no warnings as `W/libc:  memalign(64, 411042816) failed: returning null pointer` by their Android, we will be crazy.  BTW, memory alignment is factually a good way for efficiency, but we may need to consider about some other ways for a big memory alignment problem. Looking for your reply, thx.

**Comment by renjie-liu** [comment]
Hi Benoit, can you help take a look? thanks!

**Comment by bjacob** [comment]
Hi, thanks for filing this issue. Please let me know if PR #258 addresses it, or did you have something else in mind? With PR #258:
* If exception handling is enabled (as in the compiler flag `-fexceptions`, which is default in most compilers), on allocation failure you will get a message on `stderr` followed by an exception, which you can then `catch`.
* If exception handling is disabled (as in the compiler flag `-fno-exceptions`, as is typical in Google software and likely the case when TFLite is built using Bazel), you get a fatal error (message printed to `stderr`, followed by `abort()`).

Example error message:
```
EXCEPTION: ruy/ruy/system_aligned_alloc.cc:49: SystemAlignedAlloc failed to allocate 9223372036854775807 bytes
```

**Comment by SunAriesCN** [comment]
Well, thanks @bjacob ! Your PR is look good to me. But I'm strange how to ensure the android must print this error, is that TFLite in charge? @renjie-liu If it is, we can back to  [this](https://github.com/tensorflow/tensorflow/issues/47712), and discuss whether we should catch this exception and consider the design to run some big models in Mobile, because we have some application scenarios on running the big models with TFLite under the background threads.

**Comment by bjacob** [comment]
Exception handling is generally disabled in google software ([link](https://google.github.io/styleguide/cppguide.html#Exceptions)) so I was only providing support for that for the benefit of third-party software, not tflite.

I wasn't paying attention to the fact that `stderr` is not visible by default for android intents.  I can see that printing to logcat doesn't look that hard to do ([link](https://stackoverflow.com/questions/4629308/any-simple-way-to-log-in-android-ndk-code/53239909)) so i guess i will give it a try.

**Comment by SunAriesCN** [comment]
Well, sound like bad. Here we have two ideas for this:
- Create something like [MinimalLogger](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/minimal_logging.h#L36) and [ErrorReport](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/stderr_reporter.h#L26). The logger interfaces like them may help a lot for different platforms.
- Other choice is re-design our SystemAlignedAlloc interfaces to return some info, such as [TFLiteStatus](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api_types.h#L44), about how it's going to user calling Ruy.

Above is all I can see now on my mind, thanks......( T _ T )

**Comment by bjacob** [comment]
Thanks for the ideas. I've updated PR #258 so it now reports the error on the android log as in TFLite's MinimalLogger. And I've removed the exception-handling stuff which seems like no one would use at the moment. How does this look?

**Comment by SunAriesCN** [comment]
Hi, @bjacob Sorry for my late reply, would you mind give me a command line to build your `ruy:system_aligned_alloc_test`. 
I get error `/usr/bin/ld.gold: error: cannot find -llog`, when I run the command.
```
bazel build --crosstool_top=//external:android/crosstool //ruy:system_aligned_alloc_test
```

**Comment by bjacob** [comment]
sorry, i've never managed to make android builds with bazel myself. on the other hand, we now have a CMake build, and that supports Android like in any other CMake based project.
