### ISSUE TITLE
Eigen Matrix-vector multiplication shows better performance

### ISSUE THREAD

**Issue by mharshe** [google/ruy#262]
I'm testing the performance of Eigen vs ruy on an intel machine and on a raspberry pi, and in my benchmarking tests I consistently get Eigen to perform much faster than ruy. Is there something I'm doing wrong in these benchmarks.

I'm pasting my test code below : 
```c++
class RuyMultiplier {
public:
RuyMultiplier(size_t stateSize, size_t outputSize, const std::vector<float>& weightData, int numThreads)
    :_weight(weightData) {
        context.set_max_num_threads(numThreads);
        ruy::MakeSimpleLayout(1, stateSize, ruy::Order::kColMajor, A.mutable_layout());
        ruy::MakeSimpleLayout(outputSize, stateSize, ruy::Order::kColMajor, B.mutable_layout());
        ruy::MakeSimpleLayout(1, outputSize, ruy::Order::kColMajor, C.mutable_layout());
        B.set_data(_weight.data());
        B.set_cache_policy(ruy::CachePolicy::kAlwaysCache);
    }

    void multiply(const float* state, std::vector<float>& output) {
        A.set_data(state);
        C.set_data(output.data());
        ruy::Mul(A, B, mul_params, &context, &C);
    }

private:
    std::vector<float> _weight;
    ruy::Matrix<float> A;
    ruy::Matrix<float> B;
    ruy::Matrix<float> C;
    ruy::MulParams<float, float> mul_params;
    ruy::Context context;
};
```

My function for benchmarking (using google benchmark) is: 
```c++
static void RuyBenchmark(benchmark::State& state) {
    std::random_device random_device;
    auto rng = std::mt19937(random_device());
    auto f32rng = std::bind(std::uniform_real_distribution<float>(-1.0f, +1.0f), std::ref(rng));

    size_t inputSize = state.range(0);
    size_t outputSize = state.range(1);
    std::vector<float> weight(inputSize * outputSize);

    std::generate(weight.begin(), weight.end(), std::ref(f32rng));
    RuyMultiplier testMul(inputSize, outputSize, weight, 4);

    std::vector<float> input(inputSize, 0.0f);
    std::vector<float> output(outputSize);

    float sampleValue(.0f);
    for (auto _ : state) {
        std::generate(input.begin(), input.end(), std::ref(f32rng));
        testMul.multiply(input.data(), output);
        sampleValue = output[0]; 
    }
}
```
The Eigen setup is similar but i get at much faster results. In the sample run here, my input vector has size 80, and the output vector has size 128 (so a 1x80x128 multiplication  .. or a 128 x 80 x 1 multiplication, depending on whether i treat is as row major or column major)

```bash
-----------------------------------------------------------------------------------------------
Benchmark                                                     Time             CPU   Iterations
-----------------------------------------------------------------------------------------------
RuyBenchmark/I:80/H:128/process_time/real_time         62.8 us         62.9 us        10469
EigenBenchmark/I:80/H:128/process_time/real_time       1.66 us         1.66 us       416765
```

**Comment by fwz-fpga** [comment]
Hello, on arm which performance is better? You test fp32 or int8?

**Comment by bjacob** [comment]
In the benchmark loop

```
for (auto _ : state) {
        std::generate(input.begin(), input.end(), std::ref(f32rng));
        testMul.multiply(input.data(), output);
        sampleValue = output[0]; 
    }
```

I would guess that a substantial fraction of the time is spent in the `std::generate`, because mersenne twister (`std::mt19937`) is an expensive calculation.

**Comment by mharshe** [comment]
Correct, the mersenne twister would take up a lot of time, however, in my tests the benchmark loop is the same for Eigen and ruy. So the time spent in std::generate for Eigen and ruy is the same.

**Comment by bjacob** [comment]
A reason why ruy isn't optimal on matrix*vector cases is that it always packs each source matrix into fixed-size tiles to match the requirements of the kernel. These are often 8-wide, meaning that the vector here gets widened from Nx1 to Nx8. You could say that ruy just isn't optimized very hard for the matrix*vector case.

You could check if that's what is happening here by running with ruy tracing enabled. Build your benchmark with `-DRUY_TRACE` and set the number of benchmark iterations to just 1.
