### ISSUE TITLE
block_map compilation error (VS2019)

### ISSUE THREAD

**Issue by gooderist** [google/ruy#263]
I'm seeing a strange compiler error when building the face_mesh_cpu example from mediapipe using VS2019.

```
ERROR: C:/users/will/_bazel_will/mvh33bjd/external/ruy/ruy/BUILD:295:11: Compiling ruy/block_map.cc failed: (Exit 2): cl.exe failed: error executing command C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 28 argument(s) skipped)
cl : Command line warning D9002 : ignoring unknown option '-O3'
external/ruy/ruy/block_map.cc(334): error C2059: syntax error: ')'
external/ruy/ruy/block_map.cc(334): error C2676: binary '==': 'const ruy::CpuCacheParams' does not define this operator or a conversion to a type acceptable to the predefined operator
```
At block_map.cc:334, if I remove the newline before `cpu_cache_params` and put the return statement all on one line, the code compiles fine. Why on earth would whitespace cause this compilation error to happen?

For reference, the command used to build the mediapipe example is `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="[path to python3.exe]" //mediapipe/examples/desktop/face_mesh:face_mesh_cpu`

**Comment by hector1987** [comment]
same error problem.
fix comment like below, compiles fine.
  // `cols`, by omitting to divide them by the rectangularness factors.ß
  // `cols`, by omitting to divide them by the rectangularness factors.

https://github.com/google/ruy/blob/09ff5c2b2040071149a23093cd0ae6c035670235/ruy/block_map.cc#L333

**Comment by talumbau** [comment]
Thanks for this report @gooderist  and @hector1987 !  Incoming fix in https://github.com/google/ruy/pull/264

**Comment by talumbau** [comment]
Closed via https://github.com/google/ruy/pull/264
