### ISSUE TITLE
Are there any documentations?

### ISSUE THREAD

**Issue by shkatebi97** [google/ruy#265]
Hi. Is there any documentation for ruy somewhere?

I'm having trouble understanding how the ruy works. I'm trying to compare the performance of different GEMM libraries (like ruy) on mobile devices using tflite, but I'm having trouble understanding ruy and how to replace it.

Can you point me to any documentation or any guide for ruy?

**Comment by bjacob** [comment]
There isn't really documentation, but there are examples in the `example/` directory.
For performance data, we discussed that in issue #270.
