### ISSUE TITLE
How do I install this library on an arm_32 machine?

### ISSUE THREAD

**Issue by johncblacker** [google/ruy#277]
I've gone through the build process:  bazel build :all and looks like it completed successfully.  Now, though, how do I install the output of the build?  I was expecting something like a .so file, but I don't see one so I'm not sure how to install?  I don't see a bazel "install" option...

**Comment by bjacob** [comment]
First - as all the actual ruy stuff is in a `ruy/` subdir, the wildcard to build all including subdirs is `bazel build //...`

Bazel doesn't (AFAIK) have a notion of install.

We do support building with CMake too, though, and since #309 that now supports installing.
