### ISSUE TITLE
Compilation fails with GCC on ARM CortexA72 because of asm impossible constraints

### ISSUE THREAD

**Issue by jdapena** [google/ruy#284]
Trying to build Chromium with NEON on Raspberry pi 4 with Yocto and GCC (using mcpu=cortex-a7, mfpu=neon-vfpv4, mthumb), compilation of ruy fails:

```
arm-poky-linux-gnueabi-g++  -mthumb -mfpu=neon-vfpv4 -mfloat-abi=hard -mcpu=cortex-a7 -fstack-protector-strong   -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security -Wdate-time --sysroot=/home/dape/Development/rpi/poky-warrior/build/tmp/work/cortexa7t2h
f-neon-vfpv4-poky-linux-gnueabi/chromium-dev/97.0.4682.3-r0/recipe-sysroot -MMD -MF obj/third_party/ruy/ruy/pack_arm.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_OZONE=1 -DUSE_X11=1 -DOFFICIAL_BUILD -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFI
LE64_SOURCE -DNO_UNWIND_TABLES -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -I../chromium-97.0.4682.3 -Igen -I../chromium-97.0.4682.3/third_party/ruy/src -fno-ident -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchrono
us-unwind-tables -fPIC -pipe -pthread -march=armv7ve -mfloat-abi=hard -mtune=generic-armv7-a -mfpu=neon -mthumb -O2 -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g1 -fvisibility=hidden -Wno-inline-asm -Wno-psabi -Wno-unused-local-typedefs -Wno-maybe-uniniti
alized -Wno-deprecated-declarations -Wno-comments -Wno-packed-not-aligned -Wno-missing-field-initializers -Wno-unused-parameter -std=gnu++14 -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -Wno-narrowing -Wno-class-memaccess   -feliminate-unused-debug-types -fmacro-
prefix-map=/home/dape/Development/rpi/poky-warrior/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/chromium-dev/97.0.4682.3-r0=/usr/src/debug/chromium-dev/97.0.4682.3-r0                      -fdebug-prefix-map=/home/dape/Development/rpi/poky-warrior/build/tmp/wo
rk/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/chromium-dev/97.0.4682.3-r0=/usr/src/debug/chromium-dev/97.0.4682.3-r0                      -fdebug-prefix-map=/home/dape/Development/rpi/poky-warrior/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/chromium-dev/97.0
.4682.3-r0/recipe-sysroot=                      -fdebug-prefix-map=/home/dape/Development/rpi/poky-warrior/build/tmp/work/cortexa7t2hf-neon-vfpv4-poky-linux-gnueabi/chromium-dev/97.0.4682.3-r0/recipe-sysroot-native=  -fvisibility-inlines-hidden -c ../chromium-97.0.4682.3/
third_party/ruy/src/ruy/pack_arm.cc -o obj/third_party/ruy/ruy/pack_arm.o
../chromium-97.0.4682.3/third_party/ruy/src/ruy/pack_arm.cc: In function 'void ruy::Pack8bitColMajorForNeon4Cols(const ruy::PackParams8bit&)':
../chromium-97.0.4682.3/third_party/ruy/src/ruy/pack_arm.cc:264:3: error: 'asm' operand has impossible constraints
  264 |   asm volatile(
      |   ^~~
At global scope:
```

**Comment by bjacob** [comment]
thanks for the report... let us know if you ever figure this out.  One thing that stands out in your setup here is `-mthumb`  -- does it work without that flag and is dropping it an option for you?   I'm going to tentatively close that issue as `-mthumb` is something that we had never thought of supporting and that sounds like the kind of issue that one would run into with that.

**Comment by jdapena** [comment]
I am not testing 32bit ARM anymore, so I don't expect to have new feedback on this. Thanks anyway for taking a look!

**Comment by oberluz** [comment]
Hi, I'm trying to build PyCorak withcTensorflow 2.7.0 for arm7a and it also fails with the same error. Note the compile line does not use -mthumb. Also, this build is a docker cross-compilation. any ideas?

`  (cd /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/sandbox/processwrapper-sandbox/475/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o' -iquote external/ruy -iquote bazel-out/armv7a-opt/bin/external/ruy -iquote external/cpuinfo -iquote bazel-out/armv7a-opt/bin/external/cpuinfo -iquote external/clog -iquote bazel-out/armv7a-opt/bin/external/clog -Ibazel-out/armv7a-opt/bin/external/cpuinfo/_virtual_includes/cpuinfo -Ibazel-out/armv7a-opt/bin/external/clog/_virtual_includes/clog '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -Wall -Wextra -Wc++14-compat -Wundef '-mfpu=neon' -O3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/ruy/ruy/pack_arm.cc -o bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox arm-linux-gnueabihf-gcc failed: error executing command 
  (cd /home/eyeot-demo/.cache/bazel/_bazel_eyeot-demo/eab0d61a99b6696edb3d2aff87b585e8/sandbox/processwrapper-sandbox/475/execroot/pycoral && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin \
    PWD=/proc/self/cwd \
  /usr/bin/arm-linux-gnueabihf-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-march=armv7-a' '-mfpu=neon-vfpv4' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections -fdata-sections -funsafe-math-optimizations -ftree-vectorize '-std=c++14' -MD -MF bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.d '-frandom-seed=bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o' -iquote external/ruy -iquote bazel-out/armv7a-opt/bin/external/ruy -iquote external/cpuinfo -iquote bazel-out/armv7a-opt/bin/external/cpuinfo -iquote external/clog -iquote bazel-out/armv7a-opt/bin/external/clog -Ibazel-out/armv7a-opt/bin/external/cpuinfo/_virtual_includes/cpuinfo -Ibazel-out/armv7a-opt/bin/external/clog/_virtual_includes/clog '-DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION' '-ffp-contract=off' -Wall -Wextra -Wc++14-compat -Wundef '-mfpu=neon' -O3 -no-canonical-prefixes -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c external/ruy/ruy/pack_arm.cc -o bazel-out/armv7a-opt/bin/external/ruy/ruy/_objs/pack_arm/pack_arm.o)
Execution platform: @local_execution_config_platform//:platform

Use --sandbox_debug to see verbose messages from the sandbox
In file included from external/ruy/ruy/pack_arm.cc:16:
external/ruy/ruy/pack_arm.h:492:9: warning: multi-line comment [-Wcomment]
  492 | #endif  // (RUY_PLATFORM_NEON_64 || RUY_PLATFORM_NEON_32) && \
      |         ^
external/ruy/ruy/pack_arm.cc: In function 'void ruy::Pack8bitColMajorForNeon4Cols(const ruy::PackParams8bit&)':
external/ruy/ruy/pack_arm.cc:264:3: error: 'asm' operand has impossible constraints
  264 |   asm volatile(
      |   ^~~
Target //src:_pywrap_coral failed to build
`
