### ISSUE TITLE
How to statically link with ruy?

### ISSUE THREAD

**Issue by DanijelDomazet** [google/ruy#301]
I've built the TensorFlow Lite C API as static lib. 
I need to link with sub-dependend libs too, one of which is Ruy.
However, there are ~30 `.a` libs for Ruy. 
Do I need to link with all of those? What to do?

**Comment by bjacob** [comment]
you should only need to link to `ruy`. if that gives undefined symbol linking errors, start linking to more libraries and/or report that as a bug - though we may only be able to do anything if you're using one of the two supported build systems, Bazel and CMake.
