### ISSUE TITLE
Broken computation when running under nodejs on armv7

### ISSUE THREAD

**Issue by lissyx** [google/ruy#68]
Fuller investigation has been documented on https://github.com/tensorflow/tensorflow/issues/39509.

It looks like `q7` was removed from the clearage in https://github.com/tensorflow/tensorflow/commit/2359c4e45e1226e4a9d4072c2b7753b5ae731f44#diff-ca44636122d5fd4fe9600903ebf461b9L665.

I honestly don't know why it would expose this behavior only under NodeJS and only on ARMv7 platform, but re-instating `q7` as in https://github.com/tensorflow/tensorflow/pull/39951 fixes the issue.

Since `q7` is cleared at other places `q6-q15` are cleared, and since there's no specific comment regarding the removal of `q7` at this place, is it possible it's just a slight typo and I have been lucky in finding it?

**Comment by bjacob** [comment]
Thanks for the fix. I'm curious. You are running nodejs on arm32? Is your hardware supporting only arm32 and not arm64 code? You will get higher performance with arm64 code, especially for the code path that you're fixing here, which is the quantized 8bit path, when running arm64 code ruy is able to take advantage of new [ARM dot-product instructions](https://community.arm.com/developer/tools-software/tools/b/tools-software-ides-blog/posts/exploring-the-arm-dot-product-instructions), a 4x speedup.  ruy takes care automatically of detecting whether these instructions are available and use them when appropriate.

**Comment by lissyx** [comment]
I'm not targeting any specific hw, I was looking into leveraging threads for running on some Cortex-A53 SoC like Rpi3, as well as QM215. NodeJS is just one of our bindings for deepspeech, and I ran into the issue when pushing to our CI 😊

**Comment by bjacob** [comment]
OK. Just a generic note that ruy will benefit from running arm64 code. In particular, Cortex-A53 is arm64-capable. QM215 is A53-based too.

**Comment by lissyx** [comment]
> OK. Just a generic note that ruy will benefit from running arm64 code. In particular, Cortex-A53 is arm64-capable. QM215 is A53-based too.

Indeed but on those two examples, raspbian is running in 32 bits and Android 10 Go as well, but thanks for your advice.

**Comment by bjacob** [comment]
i see, thanks for the explanation. knowing this helps prioritize arm32 in future ruy work.
